### ISSUE TITLE
[BUG] Autogguf window is bigger than my display resolution 1920x1080p

### ISSUE THREAD

**Issue by JohnClaw** [leafspark/AutoGGUF#14]
I can't work comfortably because Autogguf window can't be resized or be fitted to screen size, maximize/minimize window function also is absent.
![image](https://github.com/user-attachments/assets/a1473f22-5b2e-40a5-860c-cdd1ee9838d7)

**Comment by leafspark** [comment]
Thanks for bringing this to my attention and for the screenshot!

You can try these workarounds for now:

- Ctrl- and Ctrl+ (or Ctrl=) are avaliable to expand or reduce the window size
- You can create a .env file inside the AutoGGUF directory with this parameter:
   - `AUTOGGUF_RESOLUTION=1242x828`
  
The issue where there's no scaling by mouse is an issue I'm working on fixing, since it's a result of the custom UI frame. I'm hoping to complete it by the next release.
